### PR TITLE
Joey chromosomes fix

### PR DESCRIPTION
**Pull request by joeygiordano13**
@suneettipirneni @APherwani scaling should be fine now. The only weird stuff is that certain chromosomes start with their centromere (I think this is due to some of the staining values being off, so i'll fix that in my next PR). I made sure the meshes all abide by the affine transformation protocol. I'll do a writeup on this for the docs later.

### CODE REVIEW

**Comment by APherwani** [comment]
> @suneettipirneni @APherwani scaling should be fine now. The only weird stuff is that certain chromosomes start with their centromere (I think this is due to some of the staining values being off, so i'll fix that in my next PR). I made sure the meshes all abide by the affine transformation protocol. I'll do a writeup on this for the docs later. 

@joeygiordano13 can you make the fix in this PR? It's okay if you cannot.

**Comment by joeygiordano13** [comment]
I was going to save it for when I modify the UCSC schema JSON, which will include adding the X and Y chromosome. That might be finished by @Maxgundam later so I say save it for the next relevant PR. Looking to get this in main quickly since I've dragged it out so long at this point. @APherwani

**Comment by APherwani** [comment]
Understood. Starting review

**Review by APherwani — APPROVED** [review]
Slight thing. Some chromosomes start with the centromeres as you mentioned. But some chromosomes top part is cut off.

**Pull request merged**
